#pragma once

typedef enum {
    STATE_SUCCESS=0,
    STATE_ERR_UNKNOWN=-1,
    STATE_ERR_MEMORY=-2,
    STATE_ERR_IO =-3,
    STATE_ERR_RUNTIME=-4,
    STATE_ERR_INDEX=-5,
    STATE_ERR_DIVIDE_BY_ZERO=-6,
    STATE_ERR_OVERFLOW =-7,
    STATE_ERR_VALUE =-8,
    STATE_ERR_SYSTEM =-9
} state_status_t;
